name: Deploy Backend no Render

on:
  push:
    branches:
      - main 
    paths:
      - 'backend/**' 

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Acionar Deploy Hook do Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}